#!/usr/bin/env python3
"""Build the complete index.html"""
import os
os.chdir('/root/.openclaw/workspace/projects/ai-pet-portal')

# Build from parts
with open('index.html', 'w', encoding='utf-8') as out:
    # Head
    with open('head.txt', 'r', encoding='utf-8') as f:
        out.write(f.read())
    # CSS
    with open('css_inline.txt', 'r', encoding='utf-8') as f:
        out.write(f.read())
    
    # Navbar
    out.write('''<nav class="navbar"><div class="container"><a href="#" class="logo">AI Pet <span>Studio</span></a><ul class="nav-links"><li><a href="#styles">艺术风格</a></li><li><a href="#how">如何使用</a></li><li><a href="#features">为什么选择</a></li><li><a href="#faq">常见问题</a></li><li><a href="#" class="nav-cta" onclick="openModal();return false;">立即生成</a></li></ul></div></nav>''')
    
    # Hero
    out.write('''<section class="hero"><div class="container"><div class="hero-grid"><div class="hero-text"><h1>把你的宠物变成<br><span class="gradient-text">艺术明星 ✨</span></h1><p>上传宠物照片，选择喜欢的艺术风格，AI 在 2 分钟内为你生成专业级宠物艺术照。12+ 种风格可选，完全免费！</p><div class="hero-badges"><span class="badge"><svg width="13" height="13" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg> 无需注册</span><span class="badge"><svg width="13" height="13" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg> 2分钟完成</span><span class="badge"><svg width="13" height="13" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg> 12+ 风格</span><span class="badge"><svg width="13" height="13" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14"/></svg> 免费下载</span></div><div class="upload-zone" id="heroUpload" onclick="document.getElementById('fileInput').click()"><div class="icon"><svg fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg></div><h3>上传宠物照片</h3><p>拖拽照片到此处，或点击选择文件</p><div class="formats"><span class="format-tag">JPG</span><span class="format-tag">PNG</span><span class="format-tag">WEBP</span></div></div></div><div class="hero-visual"><div class="hero-gallery" id="heroGallery"></div></div></div></div></section>''')
    
    # Stats bar
    out.write('''<div class="stats-bar"><div class="container"><div class="stats-grid"><div class="stat-item"><h3>50万+</h3><p>成功生成艺术照</p></div><div class="stat-item"><h3>12+</h3><p>精选艺术风格</p></div><div class="stat-item"><h3>~2分钟</h3><p>平均生成时间</p></div><div class="stat-item"><h3>100%</h3><p>免费无水印</p></div></div></div></div>''')
    
    # Style gallery
    out.write('''<section class="section" id="styles"><div class="container"><div class="section-header"><span class="section-label">✨ 艺术风格</span><h2>12 种艺术风格，任你挑选</h2><p>每种风格都经过专门优化，为你的宠物打造专属艺术效果</p></div><div class="style-grid" id="styleGrid"></div></div></section>''')
    
    # How it works
    out.write('''<section class="section how-it-works" id="how"><div class="container"><div class="section-header"><span class="section-label">🚀 三步完成</span><h2>简单三步，生成艺术照</h2><p>无需任何技术背景，只需几步操作即可完成</p></div><div class="steps-grid"><div class="step-card animate-in"><div class="step-number">1</div><h3>上传照片</h3><p>点击上传按钮，选择你的宠物照片，支持 JPG、PNG、WEBP 格式</p></div><div class="step-card animate-in"><div class="step-number">2</div><h3>选择风格</h3><p>从 12 种精选艺术风格中挑选喜欢的风格：油画、卡通、像素等</p></div><div class="step-card animate-in"><div class="step-number">3</div><h3>下载作品</h3><p>AI 自动生成艺术照，预览满意后一键下载，高清无水印</p></div></div></div></section>''')
    
    # Features
    out.write('''<section class="section" id="features"><div class="container"><div class="section-header"><span class="section-label">💎 核心优势</span><h2>为什么选择 AI Pet Studio</h2><p>专业的 AI 技术，让每只宠物都成为艺术明星</p></div><div class="features-grid"><div class="feature-card animate-in"><div class="feature-icon"><svg fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M13 10V3L4 14h7v7l9-11h-7z"/></svg></div><h3>极速生成</h3><p>先进的 AI 算法，平均 2 分钟内完成艺术照生成，无需漫长等待</p></div><div class="feature-card animate-in"><div class="feature-icon"><svg fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M4.5 12.75l6 6 9-13.5"/></svg></div><h3>高清无水印</h3><p>生成高分辨率艺术照片，无水印、无压缩，适合打印和社交分享</p></div><div class="feature-card animate-in"><div class="feature-icon"><svg fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg></div><h3>12+ 精选风格</h3><p>从巴比娃娃到浮世绘，从油画到赛博朋克，总有一款适合你的宠物</p></div><div class="feature-card animate-in"><div class="feature-icon"><svg fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/></svg></div><h3>操作简单</h3><p>无需注册、无需下载插件，网页端直接使用，随时随地创作</p></div><div class="feature-card animate-in"><div class="feature-icon"><svg fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg></div><h3>隐私保护</h3><p>照片仅用于本次生成处理，不会上传存储到任何第三方服务器</p></div><div class="feature-card animate-in"><div class="feature-icon"><svg fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg></div><h3>完全免费</h3><p>所有功能完全免费使用，无隐藏收费，无使用次数限制</p></div></div></div></section>''')
    
    # Testimonials
    out.write('''<section class="section testimonials"><div class="container"><div class="section-header"><span class="section-label">💬 用户评价</span><h2>宠物主人都在用</h2><p>看看他们如何用 AI Pet Studio 为毛孩子创造艺术</p></div><div class="testimonials-grid"><div class="testimonial-card animate-in"><div class="testimonial-stars">★★★★★</div><div class="testimonial-text">"AI Puppy 太棒了！巴比娃娃风格特别受欢迎，每只宠物都能变成艺术品。"</div><div class="testimonial-author"><div class="testimonial-avatar">陈</div><div><div class="testimonial-name">陈莎拉</div><div class="testimonial-role">宠物摄影师</div></div></div></div><div class="testimonial-card animate-in"><div class="testimonial-stars">★★★★★</div><div class="testimonial-text">"油画风格让每只宠物都显得高贵优雅，客户都很喜欢，已经推荐给很多朋友了。"</div><div class="testimonial-author"><div class="testimonial-avatar">迈</div><div><div class="testimonial-name">迈克·罗德里格斯</div><div class="testimonial-role">宠物店老板</div></div></div></div><div class="testimonial-card animate-in"><div class="testimonial-stars">★★★★★</div><div class="testimonial-text">"我的猫咪在社交媒体上火了！用各种风格的照片获得了数万点赞，太神奇了。"</div><div class="testimonial-author"><div class="testimonial-avatar">李</div><div><div class="testimonial-name">李萨汤普森</div><div class="testimonial-role">宠物博主</div></div></div></div><div class="testimonial-card animate-in"><div class="testimonial-stars">★★★★★</div><div class="testimonial-text">"乐高风格的照片太有趣了！打印出来装饰房间，朋友们都觉得超酷。"</div><div class="testimonial-author"><div class="testimonial-avatar">朴</div><div><div class="testimonial-name">朴大卫</div><div class="testimonial-role">宠物主人</div></div></div></div><div class="testimonial-card animate-in"><div class="testimonial-stars">★★★★★</div><div class="testimonial-text">"作为设计师，我经常需要宠物相关的创意素材。AI Puppy 让我的工作效率大大提升。"</div><div class="testimonial-author"><div class="testimonial-avatar">威</div><div><div class="testimonial-name">艾玛威尔逊</div><div class="testimonial-role">设计师</div></div></div></div><div class="testimonial-card animate-in"><div class="testimonial-stars">★★★★★</div><div class="testimonial-text">"快速、准确，每次都有惊艳的效果。已经成为我创作宠物内容的必备工具。"</div><div class="testimonial-author"><div class="testimonial-avatar">金</div><div><div class="testimonial-name">詹姆斯金</div><div class="testimonial-role">宠物内容创作者</div></div></div></div></div></div></section>''')
    
    # FAQ
    out.write('''<section class="section" id="faq"><div class="container"><div class="section-header"><span class="section-label">❓ 常见问题</span><h2>有疑问？看这里</h2><p>我们对常见问题进行了整理，方便你快速找到答案</p></div><div class="faq-list"><div class="faq-item"><button class="faq-question" onclick="toggleFaq(this)">什么是 AI Pet Studio，它是如何工作的？<svg width="18" height="18" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M19 9l-7 7-7-7"/></svg></button><div class="faq-answer"><div class="faq-answer-inner">AI Pet Studio 使用人工智能技术识别宠物的特征，然后将其转换为各种艺术风格。我们的算法能够准确识别不同宠物的外观，同时应用巴比娃娃、油画、卡通、动漫等艺术效果。</div></div></div><div class="faq-item"><button class="faq-question" onclick="toggleFaq(this)">支持哪些宠物类型？<svg width="18" height="18" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M19 9l-7 7-7-7"/></svg></button><div class="faq-answer"><div class="faq-answer-inner">AI Pet Studio 支持所有常见宠物类型，包括猫咪、狗狗、兔子、仓鼠、鸟类、龙猫等。我们的 AI 能够识别不同宠物的特征并生成相应的艺术风格照片。</div></div></div><div class="faq-item"><button class="faq-question" onclick="toggleFaq(this)">生成的照片质量如何？<svg width="18" height="18" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M19 9l-7 7-7-7"/></svg></button><div class="faq-answer"><div class="faq-answer-inner">我们生成高分辨率的宠物艺术照片，适合打印和专业用途。每张生成的照片都保持宠物的独特特征，同时具有专业的艺术效果，无水印、无压缩。</div></div></div><div class="faq-item"><button class="faq-question" onclick="toggleFaq(this)">支持哪些艺术风格？<svg width="18" height="18" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M19 9l-7 7-7-7"/></svg></button><div class="faq-answer"><div class="faq-answer-inner">我们提供 12 种精选艺术风格，包括：巴比娃娃风格、油画艺术风格、卡通动漫风格、像素艺术风格、乐高积木风格、素描风格、水彩画风格、赛博朋克风格、童话绘本风格、复古胶片风格、浮世绘风格、梦幻星尘风格。</div></div></div><div class="faq-item"><button class="faq-question" onclick="toggleFaq(this)">生成需要多长时间？<svg width="18" height="18" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M19 9l-7 7-7-7"/></svg></button><div class="faq-answer"><div class="faq-answer-inner">大多数宠物艺术照生成在 1-3 分钟内完成，具体取决于选择的风格和图像复杂性。我们优化的 AI 模型确保快速处理而不影响质量。</div></div></div><div class="faq-item"><button class="faq-question" onclick="toggleFaq(this)">生成的图片可以商用吗？<svg width="18" height="18" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M19 9l-7 7-7-7"/></svg></button><div class="faq-answer"><div class="faq-answer-inner">生成的图片可免费用于个人和商业用途，包括社交媒体分享、打印装饰、制作个性化礼品、宠物纪念品等。所有照片均为高分辨率无水印版本。</div></div></div></div></div></section>''')
    
    # CTA
    out.write('''<section class="cta-section"><div class="container"><h2>让您的宠物成为艺术明星 🐾</h2><p>上传照片，选择风格，几分钟内获得专业级宠物艺术照</p><a href="#" class="cta-btn" onclick="openModal();return false;"><svg width="20" height="20" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14"/></svg>立即开始免费生成</a></div></section>''')
    
    # Footer
    out.write('''<footer class="footer"><div class="container"><div class="footer-grid"><div class="footer-brand"><a href="#" class="logo">AI Pet <span>Studio</span></a><p>专业级 AI 宠物艺术照生成平台。将你的宠物照片转换为巴比娃娃、油画、卡通、动漫、像素艺术等多种精美风格。</p></div><div class="footer-links"><h4>快速链接</h4><ul><li><a href="#styles">艺术风格</a></li><li><a href="#how">如何使用</a></li><li><a href="#features">核心优势</a></li><li><a href="#faq">常见问题</a></li></ul></div><div class="footer-links"><h4>法律信息</h4><ul><li><a href="#">隐私政策</a></li><li><a href="#">服务条款</a></li><li><a href="#">联系我们</a></li></ul></div></div><div class="footer-bottom"><p>© 2026 AI Pet Studio. All rights reserved. 用 ❤️ 为宠物打造艺术。</p></div></div></footer>''')
    
    # Modal
    out.write('''<div class="modal-overlay" id="modalOverlay"><div class="modal"><div class="modal-header"><div class="modal-title" id="modalTitle">AI 宠物艺术照生成</div><button class="modal-close" onclick="closeModal()"><svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M18 6L6 18M6 6l12 12"/></svg></button></div><div class="modal-body"><div class="step-indicator" id="stepIndicator"><div class="step-dot active" id="dot1"></div><div class="step-dot" id="dot2"></div><div class="step-dot" id="dot3"></div></div><div id="step1"><div class="api-notice"><strong>注意：</strong>请在代码中将 <code>API_KEY</code> 替换为您的阿里云通义万相 API Key 后使用。</div><div class="preview-area" id="previewArea"><img id="previewImg" src="" alt="预览"></div><div class="modal-style-grid" id="modalStyleGrid"></div><button class="btn-generate" id="generateBtn" onclick="startGeneration()" disabled>请先上传照片并选择风格</button></div><div id="step2" style="display:none"><div class="loading-state"><div class="loading-spinner"></div><div class="loading-style-name" id="loadingStyleName">正在生成...</div><div class="loading-text">AI 正在为您的宠物创作艺术作品</div><div class="loading-pulse"><span></span><span></span><span></span></div></div></div><div id="step3" style="display:none"><div class="result-area"><div class="result-image"><img id="resultImg" src="" alt="生成结果"></div><div class="result-actions"><button class="btn-download" onclick="downloadResult()"><svg width="18" height="18" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14"/></svg>下载图片</button><button class="btn-try-again" onclick="resetModal()">再生成一张</button></div></div></div></div></div></div><input type="file" id="fileInput" accept="image/jpeg,image/png,image/webp" onchange="handleFileSelect(event)">''')
    
    # JS
    out.write('''<script>
const STYLES=[{id:"barbie",name:"巴比娃娃风格",desc:"粉色梦幻，甜美可爱",prompt:"Transform this pet into a beautiful Barbie doll style portrait, pink dreamy atmosphere, sparkling eyes, glossy hair, fashion photography style, soft lighting, pastel colors"},{id:"oil",name:"油画艺术风格",desc:"经典油画，质感厚重",prompt:"Transform this pet into a masterpiece oil painting portrait, classical art style, rich textures, dramatic lighting, museum quality, Renaissance inspired"},{id:"cartoon",name:"卡通动漫风格",desc:"动漫风格，圆润可爱",prompt:"Transform this pet into an adorable cartoon character, anime style, big expressive eyes, clean lines, vibrant colors, Japanese animation aesthetic"},{id:"pixel",name:"像素艺术风格",desc:"8-bit 复古游戏风",prompt:"Transform this pet into a pixel art character, 8-bit retro game style, nostalgic video game aesthetic, limited color palette"},{id:"lego",name:"乐高积木风格",desc:"乐高积木颗粒感",prompt:"Transform this pet into a LEGO minifigure portrait, plastic building block aesthetic, glossy surfaces, realistic LEGO materials"},{id:"sketch",name:"素描风格",desc:"铅笔素描，线条细腻",prompt:"Transform this pet into a detailed pencil sketch portrait, hand-drawn charcoal drawing, fine lines, soft shading, artistic sketchbook quality"},{id:"watercolor",name:"水彩画风格",desc:"水彩晕染，清新淡雅",prompt:"Transform this pet into a watercolor painting portrait, delicate brushstrokes, soft bleeding colors, artistic watercolor paper texture"},{id:"cyberpunk",name:"赛博朋克风格",desc:"霓虹光效，科技感",prompt:"Transform this pet into a cyberpunk style portrait, neon lights, futuristic city background, glowing LED effects, dark atmospheric lighting"},{id:"fairy",name:"童话绘本风格",desc:"插画绘本，温暖治愈",prompt:"Transform this pet into a fairy tale storybook illustration, whimsical children book art, warm lighting, magical atmosphere"},{id:"vintage",name:"复古胶片风格",desc:"胶片颗粒，怀旧色调",prompt:"Transform this pet into a vintage film photography portrait, classic film grain texture, warm nostalgic tones, 35mm film aesthetic"},{id:"ukiyoe",name:"浮世绘风格",desc:"日本浮世绘，经典东方",prompt:"Transform this pet into a traditional Japanese ukiyo-e woodblock print portrait, classic Edo period style, bold outlines, flat color areas"},{id:"stardust",name:"梦幻星尘风格",desc:"星光闪烁，梦幻唯美",prompt:"Transform this pet into a magical stardust fantasy portrait, sparkling stars and constellations, ethereal glowing atmosphere, dreamy cosmic background"}];

let selectedFile=null,selectedStyleId=null,uploadedImageBase64=null,generatedImageUrl=null;

document.addEventListener("DOMContentLoaded",()=>{renderHeroGallery();renderStyleGrid();renderModalStyles();setupScrollAnimations();setupDragDrop()});

function renderHeroGallery(){const c=document.getElementById("heroGallery");const items=[{img:"https://picsum.photos/seed/dog-h1/300/300",label:"巴比娃娃"},{img:"https://picsum.photos/seed/cat-h2/300/300",label:"油画艺术"},{img:"https://picsum.photos/seed/rabbit-h3/300/300",label:"卡通动漫"},{img:"https://picsum.photos/seed/pet4/300/300",label:"像素艺术"},{img:"https://picsum.photos/seed/hamster5/300/300",label:"乐高积木"},{img:"https://picsum.photos/seed/pet6/300/300",label:"赛博朋克"}];c.innerHTML=items.map(i=>`<div class="hero-gallery-item"><img src="${i.img}" alt="${i.label}" loading="lazy"><div class="style-label">${i.label}</div></div>`).join("")}

function renderStyleGrid(){const c=document.getElementById("styleGrid");c.innerHTML=STYLES.map(s=>`<div class="style-card" onclick="openModalWithStyle('${s.id}')"><div class="style-card-img"><img src="https://picsum.photos/seed/${s.id}-style/400/400" alt="${s.name}" loading="lazy"><div class="style-overlay"><span>选择此风格</span></div></div><div class="style-card-info"><h4>${s.name}</h4><p>${s.desc}</p></div></div>`).join("")}

function renderModalStyles(){const c=document.getElementById("modalStyleGrid");c.innerHTML=STYLES.map(s=>`<div class="modal-style-item" id="msi-${s.id}" onclick="selectStyle('${s.id}')"><img src="https://picsum.photos/seed/${s.id}-modal/300/300" alt="${s.name}" loading="lazy"><div class="mstile-name">${s.name}</div></div>`).join("")}

function setupScrollAnimations(){const o=new IntersectionObserver(e=>{e.forEach(el=>{if(el.isIntersecting)el.target.classList.add("visible")})},{threshold:0.1});document.querySelectorAll(".animate-in").forEach(el=>o.observe(el))}

function setupDragDrop(){const z=document.getElementById("heroUpload");z.addEventListener("dragover",e=>{e.preventDefault();z.classList.add("dragover")});z.addEventListener("dragleave",()=>z.classList.remove("dragover"));z.addEventListener("drop",e=>{e.preventDefault();z.classList.remove("dragover");const f=e.dataTransfer.files[0];if(f&&f.type.startsWith("image/"))processFile(f)})}

function handleFileSelect(e){const f=e.target.files[0];if(f)processFile(f)}

function processFile(file){if(!["image/jpeg","image/png","image/webp"].includes(file.type)){alert("请上传 JPG、PNG 或 WEBP 格式的图片");return}selectedFile=file;const r=new FileReader();r.onload=e=>{uploadedImageBase64=e.target.result;document.getElementById("previewImg").src=uploadedImageBase64;document.getElementById("previewArea").style.display="block";openModal()};r.readAsDataURL(file)}

function openModal(){document.getElementById("modalOverlay").classList.add("active");document.body.style.overflow="hidden";showStep1()}

function openModalWithStyle(styleId){selectedStyleId=styleId;document.getElementById("modalOverlay").classList.add("active");document.body.style.overflow="hidden";showStep1();document.querySelectorAll(".modal-style-item").forEach(el=>el.classList.remove("selected"));const el=document.getElementById("msi-"+styleId);if(el)el.classList.add("selected");updateGenerateBtn()}

function closeModal(){document.getElementById("modalOverlay").classList.remove("active");document.body.style.overflow=""}

document.getElementById("modalOverlay").addEventListener("click",e=>{if(e.target===document.getElementById("modalOverlay"))closeModal()});

function showStep1(){document.getElementById("step1").style.display="block";document.getElementById("step2").style.display="none";document.getElementById("step3").style.display="none";document.getElementById("dot1").className="step-dot active";document.getElementById("dot2").className="step-dot";document.getElementById("dot3").className="step-dot";document.getElementById("modalTitle").textContent="AI 宠物艺术照生成";if(uploadedImageBase64){document.getElementById("previewImg").src=uploadedImageBase64;document.getElementById("previewArea").style.display="block"}else{document.getElementById("previewArea").style.display="none"}}

function showStep2(){document.getElementById("step1").style.display="none";document.getElementById("step2").style.display="block";document.getElementById("step3").style.display="none";document.getElementById("dot1").className="step-dot done";document.getElementById("dot2").className="step-dot active";document.getElementById("dot3").className="step-dot";document.getElementById("modalTitle").textContent="正在生成...";const s=STYLES.find(x=>x.id===selectedStyleId);document.getElementById("loadingStyleName").textContent=s?s.name+" 风格生成中":"AI 正在创作..."}

function showStep3(){document.getElementById("step1").style.display="none";document.getElementById("step2").style.display="none";document.getElementById("step3").style.display="block";document.getElementById("dot1").className="step-dot done";document.getElementById("dot2").className="step-dot done";document.getElementById("dot3").className="step-dot active";document.getElementById("modalTitle").textContent="生成完成！"}

function selectStyle(styleId){selectedStyleId=styleId;document.querySelectorAll(".modal-style-item").forEach(el=>el.classList.remove("selected"));document.getElementById("msi-"+styleId).classList.add("selected");updateGenerateBtn()}

function updateGenerateBtn(){const btn=document.getElementById("generateBtn");const s=STYLES.find(x=>x.id===selectedStyleId);if(!selectedStyleId){btn.textContent="请先选择一种艺术风格";btn.disabled=true}else if(!uploadedImageBase64){btn.textContent=s?s.name+" - 请先上传宠物照片":"请先上传宠物照片";btn.disabled=true}else{btn.textContent=s?"生成 "+s.name+" 艺术照 ✨":"开始生成 ✨";btn.disabled=false}}

async function startGeneration(){if(!selectedStyleId||!uploadedImageBase64)return;showStep2();try{const result=await generateImage(uploadedImageBase64,selectedStyleId);generatedImageUrl=result;document.getElementById("resultImg").src=result;showStep3()}catch(err){console.error("Generation error:",err);alert("生成失败: "+err.message+"\n\n请检查 API 配置是否正确。");showStep1()}}

async function generateImage(base64Image,styleId){const style=STYLES.find(s=>s.id===styleId);const prompt="A beautiful professional pet portrait in "+style.name+" style. "+style.prompt+". High quality, detailed, stunning.";
const API_KEY="YOUR_API_KEY_HERE";const base64Data=base64Image.replace(/^data:image\/\w+;base64,/,"");const response=await fetch("https://dashscope.aliyuncs.com/api/v1/services/aigc/text2image/image-synthesis",{method:"POST",headers:{"Authorization":"Bearer "+API_KEY,"Content-Type":"application/json"},body:JSON.stringify({model:"qwen-image-2.0",input:{prompt:prompt,image_base64:base64Data},parameters:{size:"1024*1024",steps:25,seed:Math.floor(Math.random()*999999)}})});if(!response.ok){const err=await response.text();throw new Error("API Error: "+response.status)}const data=await response.json();if(data.output&&data.output.image_base64){return"data:image/jpeg;base64,"+data.output.image_base64}throw new Error("Unexpected API response format")}

function downloadResult(){if(!generatedImageUrl)return;const link=document.createElement("a");link.href=generatedImageUrl;link.download="ai-pet-"+selectedStyleId+"-"+Date.now()+".png";link.click()}

function resetModal(){selectedFile=null;selectedStyleId=null;uploadedImageBase64=null;generatedImageUrl=null;document.getElementById("fileInput").value="";document.querySelectorAll(".modal-style-item").forEach(el=>el.classList.remove("selected"));document.getElementById("previewArea").style.display="none";updateGenerateBtn();showStep1()}

function toggleFaq(btn){const item=btn.parentElement;const wasOpen=item.classList.contains("open");document.querySelectorAll(".faq-item").forEach(i=>i.classList.remove("open"));if(!wasOpen)item.classList.add("open")}

document.querySelectorAll('a[href^="#"]').forEach(a=>{a.addEventListener("click",e=>{const target=document.querySelector(a.getAttribute("href"));if(target){e.preventDefault();target.scrollIntoView({behavior:"smooth",block:"start"})}})});
</script></body></html>''')

print("Build complete!")
with open('index.html', 'r', encoding='utf-8') as f:
    content = f.read()
print(f"Total size: {len(content)} bytes")
